"""Added column in user table

Revision ID: 83f51fbc7180
Revises: 139108ee5b04
Create Date: 2026-04-02 17:11:10.066539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f51fbc7180'
down_revision: Union[str, Sequence[str], None] = '139108ee5b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_registered', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_onboarded')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_registered')
    # ### end Alembic commands ###
