"""Added words

Revision ID: f6e667501a59
Revises: a2f3e8996653
Create Date: 2026-04-04 19:27:00.277763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e667501a59'
down_revision: Union[str, Sequence[str], None] = 'a2f3e8996653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql

    word_status = postgresql.ENUM('NEW', 'LEARNING', 'LEARNED', name='word_status')
    word_status.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('example', sa.String(), nullable=False),
    sa.Column('level', postgresql.ENUM(name='levels', create_type=False), nullable=False),
    sa.Column('type', postgresql.ENUM(name='mode', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_words_id'), 'words', ['id'], unique=False)
    op.create_table('user_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', postgresql.ENUM(name='word_status', create_type=False), nullable=True),
    sa.Column('next_review_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repetition_stage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_words_id'), 'user_words', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_words_id'), table_name='user_words')
    op.drop_table('user_words')
    op.drop_index(op.f('ix_words_id'), table_name='words')
    op.drop_table('words')
    # ### end Alembic commands ###
